export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL    = "PLACE_ORDER_FAIL"
export const ORDER_RESET = "ORDER_RESET"

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST"
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS"
export const ORDER_DETAILS_FAIL    = "ORDER_DETAILS_FAIL"

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST"
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS"
export const ORDER_PAY_FAIL    = "ORDER_PAY_FAIL"
export const ORDER_PAY_RESET = "ORDER_PAY_RESET"

export const ORDER_SHIP_REQUEST = "ORDER_SHIP_REQUEST"
export const ORDER_SHIP_SUCCESS = "ORDER_SHIP_SUCCESS"
export const ORDER_SHIP_FAIL    = "ORDER_SHIP_FAIL"
export const ORDER_SHIP_RESET = "ORDER_SHIP_RESET"

export const ALL_ORDERS_REQUEST = "ALL_ORDERS_REQUEST"
export const ALL_ORDERS_SUCCESS = "ALL_ORDERS_SUCCESS"
export const ALL_ORDERS_FAIL    = "ALL_ORDERS_FAIL"
export const ALL_ORDERS_RESET = "ALL_ORDERS_RESET"