# Generated by Django 3.2.6 on 2022-02-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assign',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
