# Generated by Django 3.2.6 on 2022-03-11 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0011_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rescue',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vet',
            name='name',
        ),
        migrations.AddField(
            model_name='rescue',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vet',
            name='User',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
