# Generated by Django 3.2.6 on 2022-04-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_vet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='vet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='image',
            field=models.ImageField(blank=True, default='/def.jpg', null=True, upload_to=''),
        ),
    ]
