# Generated by Django 3.2.6 on 2022-04-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220422_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vet',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=27, null=True),
        ),
        migrations.AlterField(
            model_name='vet',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=27, null=True),
        ),
    ]
