# Generated by Django 3.2.6 on 2022-04-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_auto_20220422_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescue',
            old_name='rating',
            new_name='experience',
        ),
        migrations.AddField(
            model_name='rescue',
            name='bacground',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rescue',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='rescue',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='rescue',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
