# Generated by Django 3.2.6 on 2022-04-22 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20220422_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescue',
            old_name='experience',
            new_name='rating',
        ),
    ]
