# Generated by Django 3.2.13 on 2022-06-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20220628_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
