# Generated by Django 3.2.13 on 2022-06-28 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_vet_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rescue',
            old_name='bacground',
            new_name='background',
        ),
        migrations.AddField(
            model_name='report',
            name='rescue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.rescue'),
        ),
        migrations.AddField(
            model_name='rescue',
            name='experience',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='rescue',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
