# Generated by Django 3.2.13 on 2022-07-17 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_qualification_serviceprovider_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.CharField(blank=True, max_length=132, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availableSlots', models.JSONField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('vet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.vet')),
            ],
        ),
    ]
