# Generated by Django 3.2.13 on 2022-07-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_booking_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='details',
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
