# Generated by Django 3.2.13 on 2022-07-26 21:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0029_auto_20220717_1431'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceProvider',
            new_name='Service',
        ),
    ]
