# Generated by Django 3.2.13 on 2022-07-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_rename_serviceprovider_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
